### PR TITLE
Wip ui redesign properties

### PR DESCRIPTION
**Pull request by mjourdan**
Hi! Some more progress in implementing #356 design. Here come a bit more simple labeleditor, css tuning for the properties panel, a hint about the additional keywords, and some cleanup. There's no hurry to review ;)

### CODE REVIEW

**Comment by jflesch** [comment]
Just so you know, I tested it quickly and I saw a small bug : the header bar of the label editor dialog appears black at first. When the mouse goes over it, buttons appear.

However, I think it's most likely a Gtk/Gnome 3 bug, so I don't think there is any reason to worry about it for now.

**Comment by jflesch** [comment]
Looks perfect. Good for merge :)

**Comment by mjourdan** [comment]
> Just so you know, I tested it quickly and I saw a small bug : the header bar of the label editor dialog  appears black at first. When the mouse goes over it, buttons appear.
>
> However, I think it's most likely a Gtk/Gnome 3 bug

It seems so, as stated [here](https://github.com/jflesch/paperwork/pull/389#issuecomment-129833032)

Thanks for your prompt review!

**Comment by jflesch** [comment]
Oops, my bad, I missed this part in your comment

**Pull request merged**
